spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=test_db;encrypt=false
    username: api_user
    password: 19062006
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

server:
  port: 8080

